# Generated by Django 5.2.14 on 2026-06-18 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_rename_renderattempt_style_renderer'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Image',
        ),
    ]
